version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  allow:
    - dependency-type: "all"
  schedule:
    interval: daily
  open-pull-requests-limit: 5
  target-branch: main
  ignore:
  - dependency-name: async-websocket
    versions:
    - "> 0.8.0"
    - "< 1"
