name: Pull request
on: [pull_request]

jobs:
  Pull request:
    rubocop:
      name: scan
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up ruby
          # this should inherit from your .ruby-version
          uses: ruby/setup-ruby@v1
        - uses: actions/cache@v1
          with:
            path: vendor/bundle
            key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
            restore-keys: |
              ${{ runner.os }}-gems-
        - name: Bundle install
          run: |
            gem install bundler
            bundle config path vendor/bundle
            bundle install --jobs 4 --retry 3
        - name: Run rubocop
          run: |
            bundle exec rubocop
  rspec:
    uses: ministryofjustice/laa-reusable-github-actions/.github/workflows/rspec.yml@main

