name: Pull request
on: [pull_request]

jobs:
  rubocop:
    uses: ministryofjustice/laa-reusable-github-actions/.github/workflows/rubocop.yml@main

  rspec:
    uses: ministryofjustice/laa-reusable-github-actions/.github/workflows/rspec.yml@main

